== Thank you for reading this documentation! 
It would mean the world to all of us who poured our time, love, and efforts into this project if you would study, share, replicate, sell, remix, manufacture, mod, or otherwise interact with the D3D Pro 3D Printer. This work is released under the https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution Share-Alike 4.0 International license]. Feel free to use all of the freedoms that you are granted under that (pretty damn permissive) license. Remember to credit the contributors and share your remixes and upgrades under the same license!

== Contributors
 - Alexandria Little
 - Marcin Jakubowski, Ph.D.
 - Open Source Ecology
 - Nathan Heidt
 - Sean Marquez
 - J. Simmons, Ph.D.
 - Eric Lotze (One of the original 3D printer devs)
 - Irvin Inzurriaga (Wiring Video)
 - Jean-Baptiste Vervaeck (Graphic design of original documentation template)
 - Printables User @OK1HRA_5209 - https://www.printables.com/model/716371-parameterizable-rugged-box-in-openscad[Parameterizable rugged box in OpenScad] (CC-BY-SA-4.0)
 - Marlena Nedeljkovich
 
== A note on tool substitution
There are a lot of tools listed as 'required' in this project, but many of them can be substituted for other, simpler tools. If you do not have access to all of the nice-to-have tools that are listed in this project, feel free to adapt the instructions to what you have on hand. Please remember to be safe and use common sense!
