name: Build w/ asciidoctor & deploy to GitHub Pages

on:
  push:
    branches:
      - github-actions-deploy-issue

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: ./buildDocs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_SECRET_KEY }}
          # or github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist